basePath: /
host: localhost:8080
info:
  contact: {}
  description: API to interact with Binance public endpoints
  title: Binance API Service
  version: "1.0"
paths:
  /general/server-time:
    get:
      consumes:
      - application/json
      description: Check server time from Binance API
      produces:
      - application/json
      responses: {}
      summary: Check server time
      tags:
      - General
swagger: "2.0"
